Classes rework
Multi-Agent-io/robonomics-interface pull request #55
Opened 2022-05-12 23:38 UTC by PaTara43

Big library rework: each module has a dedicated class now, easy RWS support, new docs, new README

2022-05-13 09:43 UTC, timofeev41 requested changes

2022-05-13 09:43 UTC, timofeev41 commented on robonomicsinterface/classes/account.py
> +            raise NoPrivateKey("No private key was provided, unable to determine account address")
См. прошлый комментарий

2022-05-13 09:43 UTC, timofeev41 commented on robonomicsinterface/classes/common_functions.py
> +        )
Вообще, так как либа будет еще перерабатываться, что-то будет меняться, то лучше явно указывать какой аргумент куда передается. Что-то типа:
```python
def func(a: int, b: str) -> None:
    pass

func(a=123, b="string")
```
Зачем? Если ты потом захочешь поменять порядок аргументов, тебе придется вносить изменения во все места, где вызывается измененная функция / метод

2022-05-13 09:43 UTC, timofeev41 commented on robonomicsinterface/classes/digital_twin.py
> +        topic_hashed: str = dt_encode_topic(topic)
перед тем как что-то хешировать лучше сначала проверить dt_map

2022-05-13 09:43 UTC, timofeev41 commented on robonomicsinterface/classes/liability.py
> +        return f"0x{self.account.keypair.sign(technics_scale + economics_scale).hex()}"
Все штуки которые что-то превращают в hex у тебя вынесены в utils, почему эта осталась тут?

2022-05-13 09:43 UTC, timofeev41 commented on robonomicsinterface/classes/liability.py
> +        return f"0x{self.account.keypair.sign(index_scale + technics_scale).hex()}"
см выше

2022-05-13 09:43 UTC, timofeev41 commented on robonomicsinterface/classes/pubsub.py
> +    def listeners(
лучше использовать глаголы при объявлении методов/функций, что-то типа get_listeners

2022-05-13 09:43 UTC, timofeev41 commented on robonomicsinterface/classes/pubsub.py
> +    def peer(self, result_handler: tp.Optional[tp.Callable] = None) -> tp.Dict[str, tp.Union[str, int]]:
см выше

2022-05-13 09:43 UTC, timofeev41 commented on robonomicsinterface/classes/pubsub.py
> +    ) -> tp.Dict[str, tp.Union[str, tp.List[str], int]]:
слишком большая аннотация, можно вынести в Types и брать оттуда

2022-05-13 09:43 UTC, timofeev41 commented on robonomicsinterface/classes/reqres.py
> +class ReqRes(BaseClass):
в классе вообще нет аннотаций типов для возвращаемых значений

2022-05-13 09:43 UTC, timofeev41 commented on robonomicsinterface/classes/service_functions.py
> +        params: tp.Optional[tp.Union[tp.List[tp.Union[str, int]], str, int]] = None,
огроменная аннотация, вынеси в types

2022-05-13 09:43 UTC, timofeev41 commented on robonomicsinterface/classes/service_functions.py
> +            [params] if params is not None else None,
```python
[params] if params else None
``` 
?

2022-05-13 09:43 UTC, timofeev41 commented on robonomicsinterface/classes/service_functions.py
> +    ) -> dict:
Где-то используются аннотации Typing, где-то просто питоновские. Лучше определиться, какие ты будешь использовать в проекте

2022-05-13 09:43 UTC, timofeev41 commented on robonomicsinterface/classes/subscriptions.py
> +                        self._callback(events["event"]["attributes"])  # address-targeted
Эту штуку можно красивее сделать, например проверить что update_nr == 0 и тогда просто вернуть None, в противном случае делать все остальное. Сразу -1 уровень индентации и визуально приятнее

2022-05-13 09:43 UTC, timofeev41 commented on robonomicsinterface/decorators.py
> +            res = func(ri_instance, *args, **kwargs)
Ошибки не логгируются

2022-05-13 09:43 UTC, timofeev41 commented on robonomicsinterface/robonomics_interface_io.py
>  def callback(data):
отсутствуют аннотации типов

2022-05-13 09:43 UTC, timofeev41 commented on robonomicsinterface/types.py
> +TypeRegistryTyping = tp.Dict[str, tp.Dict[str, tp.Union[str, tp.Any]]]
Нужно ли везде добавлять Typing в конце? Я бы рассмотрел вариант с AccountDict или AccountData, например

2022-05-13 09:43 UTC, timofeev41 commented on robonomicsinterface/utils.py
> +NodeTypes = tp.Dict[str, tp.Dict[str, tp.Union[str, tp.Any]]]
лучше вынести это в types

2022-05-13 22:19 UTC, PaTara43 commented on robonomicsinterface/classes/account.py
> +from ..exceptions import NoPrivateKey
Принято, спасибо

2022-05-13 22:29 UTC, PaTara43 commented on robonomicsinterface/classes/common_functions.py
> +        )
типа все сделать kwargs? Я думаю, что если будет меняться порядок аругментов тут, то это будет ооочень большая переработка, в ее рамках поменять порядок и сделать кварги будет мелким делом. Пока оставлю так, но на будущее учту, спасиб

2022-05-13 22:32 UTC, PaTara43 commented on robonomicsinterface/utils.py
> +NodeTypes = tp.Dict[str, tp.Dict[str, tp.Union[str, tp.Any]]]
Я хз, как это сюда попало, там вообще нет сллжных типов хаха

2022-05-13 22:34 UTC, PaTara43 commented on robonomicsinterface/decorators.py
> +            res = func(ri_instance, *args, **kwargs)
Не считаю это тут нужным, это должно оставться невидимым для пользователя (переоткрывает интерфейс, если тот по таймауту с ноды закрылся)

2022-05-13 22:35 UTC, PaTara43 commented on robonomicsinterface/classes/reqres.py
> +class ReqRes(BaseClass):
Так, это контрибьют, я на ревью не усмотрел

2022-05-13 23:03 UTC, PaTara43 commented on robonomicsinterface/classes/reqres.py
> +class ReqRes(BaseClass):
@nakata5321, добавишь? Я не знаю, какие там. И в докстринг и аннотации

2022-05-13 23:05 UTC, PaTara43 commented on robonomicsinterface/classes/service_functions.py
> +            [params] if params is not None else None,
Параметры всегда оборачиваюся в лист, даже если юзер передал лист, все нужно обернуть в лист

2022-05-13 23:08 UTC, PaTara43 commented on robonomicsinterface/classes/service_functions.py
> +    ) -> dict:
типа tp.AnyString? Это пярм моветон так делать?)
Читаемо ж, и гораздо короче

2022-05-13 23:10 UTC, PaTara43 commented on robonomicsinterface/types.py
> +TypeRegistryTyping = tp.Dict[str, tp.Dict[str, tp.Union[str, tp.Any]]]
Ну а почему нет. Обозначить, что это именно типизация

2022-05-13 23:12 UTC, PaTara43 commented on robonomicsinterface/robonomics_interface_io.py
>  def callback(data):
Типа None туда поставить? Везде..

2022-05-15 16:57 UTC, timofeev41 commented on robonomicsinterface/classes/service_functions.py
> +            [params] if params is not None else None,
а, даже так. Принял

2022-05-15 16:59 UTC, timofeev41 commented on robonomicsinterface/classes/service_functions.py
> +    ) -> dict:
я про отличия dict[] и tp.Dict[]. Первый вариант не требует typing (но нужна определенная версия питона, кажется >3.8, не уверен), второй требует (для старых версий питона). Лучше определиться и юзать только один вариант. Хотя бы в рамках одного модуля)

2022-05-15 17:01 UTC, timofeev41 commented on robonomicsinterface/classes/service_functions.py
> +    ) -> dict:
Концептуально разницы нет, но если ты решишь все tp.List, tp.Dict, tp.Tuple, tp.Optional[str] поменять на list, dict, tuple, str | None (последний вариант только для питона 3.10+), то можно избавиться от импорта typing в каждом файле и юзать его только для штук типа AnyString, Any, NoReturn и вот таких специфичных

2022-05-15 17:02 UTC, timofeev41 commented on robonomicsinterface/robonomics_interface_io.py
>  def callback(data):
Ага, даже если явно ничего не возвращаешь, энивей лучше -> None поставить. + у функции callback аргумент data без типа

2022-05-15 17:04 UTC, timofeev41 commented on robonomicsinterface/classes/common_functions.py
> +        )
Пока можно и без этого, но я вот в своем проекте столкнулся с этой штукой прямо сейчас. Изначально забил на это, теперь не очень круто получается когда меняю/удаляю аргументы

2022-05-15 17:06 UTC, timofeev41 approved these changes
Все отлично

2022-05-15 17:11 UTC, timofeev41 commented
Все еще ждем аннотации от @nakata5321 в reqres.py
Потом посмотрим еще раз, что и как

2022-05-16 12:00 UTC, nakata5321 commented
https://github.com/Multi-Agent-io/robonomics-interface/pull/55#issuecomment-1126980711


> Все еще ждем аннотации от @nakata5321 в reqres.py Потом посмотрим еще раз, что и как

Сделано в #56

2022-05-16 12:07 UTC, PaTara43 commented
@timofeev41

2022-05-16 16:07 UTC, timofeev41 commented
Теперь все супер :)

2022-05-17 09:55 UTC, merged